# Demonstration using the Breast cancer Wisconsin data

The Breast cancer Wisconsin dataset is a dataset that describe the characteristics of the cell nuclei for 569 breast lumps, and includes whether they are malignant or benign.

Source: https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Diagnostic%29

**This Jupyter notebook will put to the test the artificial neuron that was written from scratch without dependence on any ML libraries.**

In [24]:
import artificial_neuron as an
import numpy as np
import pandas as pd

from sklearn import model_selection, preprocessing

In [25]:
data=pd.read_csv("../datasets/breast-cancer-wisconsin-data/data.csv", delimiter=",")
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

Convert the target ("daignosis" column) from nominal strings ("M" and "B") to numbers (0 and 1).

In [26]:
data["diagnosis"]=preprocessing.LabelEncoder().fit(["M","B"]).transform(data["diagnosis"]) # M is 0, B is 1.

data.drop(columns="id",inplace=True)

Convert the pandas Dataframe to numpy array.

In [27]:
data=data.to_numpy()

Split into train and test sets, and also seperate into features (x) and target (y). Also ensure the shape of the input and output tensors are as expected. For features: num_features x batch_size. For target: 1 x batch_size.

In [28]:
data_train, data_test = model_selection.train_test_split(data, train_size=0.8, random_state=5)

In [29]:
print(data_train.shape)
print(data_test.shape)

(455, 31)
(114, 31)


In [30]:
data_train=data_train.T
data_test=data_test.T

print(data_train.shape)
print(data_test.shape)

(31, 455)
(31, 114)


In [31]:
x_train=data_train[1:, :]
y_train=data_train[0, :].reshape(1,-1)

x_test=data_test[1:, :]
y_test=data_test[0, :].reshape(1,-1)

# Training and evaluation

Just start with some randomly chosen hyperparameters:

* number of iterations: 10

* learning rate (step size): 0.00007

* batch size: 256

In [32]:
neuron=an.Neuron(X=x_train, Y=y_train)
neuron.train(num_iterations=10, learning_rate=7e-5, batch_size=256)

print("training accuracy: ", neuron.evaluate(X=x_train, Y=y_train, metric="accuracy"))
print("test accuracy:     ", neuron.evaluate(X=x_test, Y=y_test, metric="accuracy"), end="\n\n")

Training begins...
Training Complete!
Caution: All the activations are null values.
training accuracy:  None
Caution: All the activations are null values.
test accuracy:      None



Let's check the activations

In [33]:
print(neuron.a)

[[nan nan nan ... nan nan nan]]


We likely ran into an overflow or underflow somewhere which led to the NaNs. We can try to avoid this by tweaking our hyperparameters.

In [34]:
vaious_iterations=[50, 100, 500, 1000]
for n in vaious_iterations:
    neuron=an.Neuron(X=x_train, Y=y_train)
    neuron.train(num_iterations=n, learning_rate=7e-5, batch_size=32)

    print("training accuracy: ", neuron.evaluate(X=x_train, Y=y_train, metric="accuracy"))
    print("test accuracy:     ", neuron.evaluate(X=x_test, Y=y_test, metric="accuracy"), end="\n\n")

Training begins...
Training Complete!
training accuracy:  0.36043956043956044
test accuracy:      0.42105263157894735

Training begins...
Training Complete!
training accuracy:  0.7846153846153846
test accuracy:      0.7894736842105263

Training begins...
Training Complete!
training accuracy:  0.9142857142857143
test accuracy:      0.9035087719298246

Training begins...
Training Complete!
training accuracy:  0.9120879120879121
test accuracy:      0.8859649122807017



We can start seeing the training accuracy outpace the test accuracy by the time we are reaching 1000 iterations, so we stop there as that is possibly a sign that we are begining to overfit.

**We have 90% test accuracy after 500 iterations.**

We can play around with the other hyperparameters.

In [35]:
learning_rates=[7e-3,7e-4,7e-5,7e-6]
for lr in learning_rates:    
    neuron=an.Neuron(X=x_train, Y=y_train)
    neuron.train(num_iterations=700, learning_rate=lr, batch_size=32)

    print("training accuracy: ", neuron.evaluate(X=x_train, Y=y_train, metric="accuracy"))
    print("test accuracy:     ", neuron.evaluate(X=x_test, Y=y_test, metric="accuracy"), end="\n\n")

Training begins...
Training Complete!
Caution: All the activations are null values.
training accuracy:  None
Caution: All the activations are null values.
test accuracy:      None

Training begins...
Training Complete!
Caution: All the activations are null values.
training accuracy:  None
Caution: All the activations are null values.
test accuracy:      None

Training begins...
Training Complete!
training accuracy:  0.9098901098901099
test accuracy:      0.8859649122807017

Training begins...
Training Complete!
training accuracy:  0.6725274725274726
test accuracy:      0.6929824561403509



We can do same for batch. I will show how batch size with relatively high learning rate can also cause an overflow.

In [36]:
# truncate printout of np array much earlier.
np.set_printoptions(threshold=10)

batch_sizes=[80, 81,82,83]
for b in batch_sizes:
    neuron=an.Neuron(X=x_train, Y=y_train)
    neuron.train(num_iterations=500, learning_rate=7e-5, batch_size=b)
    
    print("training accuracy: ", neuron.evaluate(X=x_train, Y=y_train, metric="accuracy"))
    print("test accuracy:     ", neuron.evaluate(X=x_test, Y=y_test, metric="accuracy"))
    print(neuron.a, end="\n\n")

# resetting to the default.
np.set_printoptions(threshold=None)

Training begins...
Training Complete!
training accuracy:  0.9076923076923077
test accuracy:      0.8859649122807017
[[0.98915491 0.11201739 0.10422711 ... 0.8189739  0.36198044 0.62945661]]

Training begins...
Training Complete!
training accuracy:  0.9120879120879121
test accuracy:      0.8859649122807017
[[0.98987214 0.11257582 0.10552775 ... 0.82780702 0.365114   0.64058033]]

Training begins...
Training Complete!
Caution: All the activations are null values.
training accuracy:  None
Caution: All the activations are null values.
test accuracy:      None
[[nan nan nan ... nan nan nan]]

Training begins...
Training Complete!
Caution: All the activations are null values.
training accuracy:  None
Caution: All the activations are null values.
test accuracy:      None
[[nan nan nan ... nan nan nan]]



Decreasing the learning rate helps out.

In [37]:
# truncate printout of np array much earlier.
np.set_printoptions(threshold=10)

batch_sizes=[81,82]
for b in batch_sizes:
    neuron=an.Neuron(X=x_train, Y=y_train)
    neuron.train(num_iterations=500, learning_rate=7e-6, batch_size=b)
    
    print("training accuracy: ", neuron.evaluate(X=x_train, Y=y_train, metric="accuracy"))
    print("test accuracy:     ", neuron.evaluate(X=x_test, Y=y_test, metric="accuracy"))
    print(neuron.a, end="\n\n")

# resetting to the default.
np.set_printoptions(threshold=None)

Training begins...
Training Complete!
training accuracy:  0.8505494505494505
test accuracy:      0.8771929824561403
[[0.79281593 0.43818    0.37552943 ... 0.50387101 0.57332357 0.50667138]]

Training begins...
Training Complete!
training accuracy:  0.843956043956044
test accuracy:      0.8771929824561403
[[0.79717373 0.43835257 0.37617978 ... 0.50892494 0.57455212 0.51037514]]

